# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: be0fe145907c85be823c00420b722bfc292b7dc0fabbb327482b7fec5ff46df064485caeecc8a535797975be4197cee9f3072d85574359e8db8f56a0451ea8b0

test:
  secret_key_base: 34e327a7bfe45edac2e632a225ced5d9f6128a9b16f2890593589c21e85cb55b0abbe2d33377c4a456b2b5a8bc250db1bb075128ffe74224141bcb91e6dad781

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
